version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:migrate:prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4321:4321
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/mydatabase?schema=public'

volumes:
  postgres_data:
